platform :ios, '8.0'
abstract_target 'AAAA' do
pod 'AFNetworking', '~>3.0'
pod 'ReactiveCocoa', '~> 2.5'
pod 'SDWebImage', '~> 3.7.5'
pod 'JSONModel', '~> 1.0.1'
pod 'Masonry','~>0.6.1'
pod 'FLEX', '~> 2.0', :configurations => ['Debug']
pod 'ActionSheetPicker-3.0'
pod 'XAspect'
pod 'CYLTabBarController'
pod 'IQKeyboardManager', '~> 3.3.7'  #兼容IOS7
pod 'LBXScan','~> 1.1.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'MWPhotoBrowser'
pod 'M13ProgressSuite', '~> 1.2.7'
pod 'WebViewJavascriptBridge', '~> 5.0'
pod 'YYText'
pod 'TZImagePickerController'  #照片选择浏览器
pod 'UITableView+FDTemplateLayoutCell'
pod 'CocoaAsyncSocket'
target 'AIProduct'do
    target 'AIProductTests' do
        inherit! :search_paths
    end
end
#target 'AIProduct_Dev'do
#    end
end
